In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
raw_data = pd.read_csv('/Users/aryamonani/Desktop/Development/Property sales transaction project/Porperty sales transactions.csv')

/Users/aryamonani/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
raw_data.head(5)

,PARID,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYADDRESSDIR,PROPERTYADDRESSSTREET,PROPERTYADDRESSSUF,PROPERTYADDRESSUNITDESC,PROPERTYUNITNO,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,SCHOOLCODE,SCHOOLDESC,MUNICODE,MUNIDESC,RECORDDATE,SALEDATE,PRICE,DEEDBOOK,DEEDPAGE,SALECODE,SALEDESC,INSTRTYP,INSTRTYPDESC
0,0028S00066000000,3326.0,,NaN,DAWSON,ST,NaN,NaN,PITTSBURGH,PA,15213.0,47,Pittsburgh,104,4th Ward - PITTSBURGH,2013-04-23,2013-04-23,157000.0,15213,395,0,VALID SALE,DE,DEED
1,0449N00211000000,11515.0,,NaN,CLEMATIS,BLVD,NaN,NaN,PITTSBURGH,PA,15235.0,30,Penn Hills Twp,934,Penn Hills,2016-09-08,2016-08-30,123944.0,166529,171,0,VALID SALE,DE,DEED
2,0948P00264000000,2305.0,,NaN,BIG ROCK,RD,NaN,NaN,ALLISON PARK,PA,15101.0,20,Hampton Township,914,Hampton,2012-05-24,2012-05-24,135000.0,14897,420,0,VALID SALE,DE,DEED
3,1105J00228000000,408.0,,NaN,HOCHBERG,RD,NaN,NaN,MONROEVILLE,PA,15146.0,18,Gateway,879,Monroeville,2012-05-24,2012-05-24,150000.0,14897,435,0,VALID SALE,DE,DEED
4,0140R00148000000,802.0,,NaN,LINDENWOOD,DR,NaN,NaN,PITTSBURGH,PA,15234.0,22,Keystone Oaks,813,Castle Shannon,2012-06-04,2012-06-04,99900.0,14907,302,0,VALID SALE,DE,DEED

In [9]:
raw_data.describe(include = 'all') #count for some features is less, which means we have missig values.

,PARID,PROPERTYHOUSENUM,PROPERTYFRACTION,PROPERTYADDRESSDIR,PROPERTYADDRESSSTREET,PROPERTYADDRESSSUF,PROPERTYADDRESSUNITDESC,PROPERTYUNITNO,PROPERTYCITY,PROPERTYSTATE,PROPERTYZIP,SCHOOLCODE,SCHOOLDESC,MUNICODE,MUNIDESC,RECORDDATE,SALEDATE,PRICE,DEEDBOOK,DEEDPAGE,SALECODE,SALEDESC,INSTRTYP,INSTRTYPDESC
count,291596,291578.000000,291596,12010,291589,290288,5701,5876,291595,291596,291595.000000,291596.000000,291596,291596.000000,291596,290370,291596,2.893370e+05,291295,291285,291596.0,291596,291596,291596
unique,211008,NaN,1485,4,9069,48,10,1234,98,1,NaN,NaN,46,NaN,175,2279,2891,NaN,3419,1907,50.0,28,28,28
top,0431B00017000000,NaN,,N,WASHINGTON,ST,UNIT,2,PITTSBURGH,PA,NaN,NaN,Pittsburgh,NaN,Penn Hills,2012-10-26,2016-04-29,NaN,TR18,1,3.0,LOVE AND AFFECTION SALE,DE,DEED
freq,20,NaN,287438,3323,1660,74513,5259,84,158092,291596,NaN,NaN,72595,NaN,10524,594,597,NaN,1284,3127,57041.0,57041,166269,166269
mean,NaN,1438.864925,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15169.725510,29.029623,NaN,687.966334,NaN,NaN,NaN,1.712125e+05,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,2062.445662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.819925,15.067414,NaN,340.959088,NaN,NaN,NaN,9.755176e+05,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15003.000000,1.000000,NaN,101.000000,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,159.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15108.000000,17.000000,NaN,202.000000,NaN,NaN,NaN,2.500000e+02,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,602.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15204.000000,29.000000,NaN,874.000000,NaN,NaN,NaN,7.450000e+04,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1811.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15221.000000,46.000000,NaN,927.000000,NaN,NaN,NaN,1.800000e+05,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,39389.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16229.000000,50.000000,NaN,953.000000,NaN,NaN,NaN,1.487529e+08,NaN,NaN,NaN,NaN,NaN,NaN